# Generated by Django 2.1 on 2018-10-01 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='userinfo',
        ),
    ]
