# Generated by Django 2.1 on 2018-10-02 03:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20181001_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('atype', models.CharField(max_length=20, verbose_name='文章类型')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('postdate', models.DateField(default=django.utils.timezone.now, verbose_name='上传日期')),
                ('astatus', models.BooleanField(verbose_name='是否展示')),
                ('ascanning', models.IntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '文章管理',
                'verbose_name_plural': '文章管理',
                'db_table': 'article',
            },
        ),
    ]
