# Generated by Django 2.1 on 2018-10-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(default='', upload_to='main_page/static/aimg', verbose_name='文章配图'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='imgurl',
            field=models.ImageField(upload_to='main_page/static/pimg'),
        ),
    ]
