# Generated by Django 2.1 on 2018-09-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30, verbose_name='用户名')),
                ('upwd', models.CharField(max_length=20, verbose_name='用户密码')),
                ('uemail', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('uphone', models.CharField(max_length=11, verbose_name='手机号码')),
            ],
            options={
                'db_table': '用户信息',
            },
        ),
    ]
