# Generated by Django 2.1 on 2018-10-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodss', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='name',
            new_name='gname',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='desc',
        ),
        migrations.AddField(
            model_name='goods',
            name='gdesc',
            field=models.TextField(null=True, verbose_name='商品描述'),
        ),
    ]
